version: '3.8'

services:
  web:
    build:
      context: ./medical_helper
      dockerfile: Dockerfile
    command: gunicorn medical_helper.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/medical_helper/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=maksimpugacev
      - POSTGRES_PASSWORD=bNJg09maksi
      - POSTGRES_DB=hydrodynamics_bot

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/medical_helper/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: